# Windows Disks States
---
- name: Get Current Windows Disks State
  hosts: all
  gather_facts: yes
  tasks:

    - name: Check Disks Health and Sizes 
      ansible.windows.win_powershell:
        script: |
          Get-Volume | select DriveLetter,HealthStatus,Size,SizeRemaining
      register: output_var

    - name: Generate file report
      ansible.windows.win_powershell:
        script: |
          gwmi win32_logicaldisk | Format-Table DeviceId, MediaType, @{n="Size";e={[math]::Round($_.Size/1GB,2)}},@{n="FreeSpace";e={[math]::Round($_.FreeSpace/1GB,2)}} >> C:\Users\Administrator\Documents\reporteEspacioDisco_{{ ansible_date_time.date }}.txt

    - debug:
        msg:
          - "Disco: {{ output_var.output[ansible_loop.index0 - 1].DriveLetter }}"
          - "Estado: {{ output_var.output[ansible_loop.index0 - 1].HealthStatus }}"
          - "Size MB: {{ output_var.output[ansible_loop.index0 - 1].Size }}"
          - "SizeRemaining MB: {{ output_var.output[ansible_loop.index0 - 1].SizeRemaining }}"
      loop: "{{ output_var.output }}"
      loop_control:
        extended: true
        label: "{{ ansible_loop.index0 }}"

    - ansible.builtin.fetch: 
        src: C:/Users/Administrator/Documents/reporteEspacioDisco_{{ ansible_date_time.date }}.txt 
        dest: /var/
        flat: yes

    - name: Send email report
      community.general.mail:
        host: smtp.freesmtpservers.com
        port: 25
        subject: Ansible Playbook Report.
        body: |
          Reporte de entrega del estado de ejecución de Playbook sobre el host {{ ansible_hostname }}.
          En el siguiente reporte se atacha el archivo generado para su uso particular. Asimismo, parte del output visible en la consola web
          de Ansible Automation Platform.
          
          - "{{ output_var.output }}"

          Saludos.
          Nota: este reporte es auto generado y modificado según las necesidades.
        attach:
        - /var/reporteEspacioDisco_{{ ansible_date_time.date }}.txt
        from: 
        to: 
      delegate_to: localhost
