---
- name: Actualización Agente NewRelic
  hosts: all
  become: false
  gather_facts: false
  tasks:
    - name: Copy file to windows host
      ansible.builtin.copy:
        src: /prueba/newrelic-infra.msi
        dest: C:\Program Files (x86)\newrelic-infra.msi
        local_follow: yes
