---
- name: Actualización Agente NewRelic
  hosts: all
  become: false
  gather_facts: false
  tasks:
    - name: Copy file to windows host
      ansible.windows.win_copy:
        src: C:\Program Files (x86)\Common Files\System\wab32.dll
        dest: /home/ansible/
        remote_src: yes
        local_follow: yes
