---
- name: Actualización Agente NewRelic
  hosts: all
  become: false
  gather_facts: false
  tasks:
    - name: Copy file to windows host
      copy:
        src: /prueba/newrelic-infra.msi
        dest: C:\Program Files (x86)\
        remote_src: yes
        local_follow: yes
