---
- name: Actualización Agente NewRelic
  hosts: all
  become: false
  gather_facts: yes
  tasks:
  
    - name: Get State of Scheduled Tasks
      ansible.windows.win_powershell:
        script: |
          Get-ScheduledTask | Select-Object State,TaskName
      register: taskState

    - name: Print Task State
      debug:
        msg: |
          "{{ taskState }}"

