---
- name: Actualización Agente NewRelic
  hosts: all
  become: false
  gather_facts: false
  tasks:
    - name: Copy file to windows host
      ansible.windows.win_copy:
        src: /prueba/newrelic-infra.msi
        dest: C:\Users\
        remote_src: yes
