---
- name: Actualización Agente NewRelic
  hosts: all
  become: false
  gather_facts: yes
  tasks:
  
    - name: Get State of Scheduled Tasks
      ansible.windows.win_powershell:
        script: |
          Get-ScheduledTask | Where-Object -Property TaskName -match "{{ item }}" | Select-Object State,TaskName
      loop:
        - Device-Sync
        - Recovery-Check
        - Automatic-Device-Join
        - WIM-Hash-Validation
      register: taskState

    - name: Print Task State
      debug:
        var: taskState

