---
- name: Actualización Agente NewRelic
  hosts: all
  become: false
  gather_facts: false
  tasks:
    - name: Copy file to windows host
      copy:
        src: /tmp/newrelic-infra.msi
        dest: C:\newrelic-infra.msi
