---
- name: Check windows Services
  hosts: all
  gather_facts: false
  tasks:
    - name: Check status
      ansible.windows.win_powershell:
        script: |
          Get-WmiObject -Class Win32_LogicalDisk | ? {$_. DriveType -eq 3} | select DeviceID, {[int]($_.Size /1GB)}, {[int]($_.FreeSpace /1GB)}
      register: output_var
      log_path: C:\Users
