---
- name: Check windows Services
  hosts: all
  gather_facts: false
  tasks:
    - name: Deshabilitar tareas programadas CSP
      community.windows.win_scheduled_task:
        name: MicrosoftEdgeUpdateTaskMachineCore
      register: tasks_var
    
    - name: Debugging
      debug:
        msg: "{{ tasks_var }}"
