---
- name: Check windows Services
  hosts: all
  gather_facts: false
  vars_files:
    - tasks/vars.yml
  tasks:

    - name: Create Directory
      ansible.windows.win_file:
        path: D:\Automatizacion_Ansible\Revision_Ambiente\Servicios
        state: directory
        
    - name: Reporte Servicios Activos
      ansible.windows.win_powershell:
        script: |
            $services = New-Object System.Collections.ArrayList

            foreach ($service in (Get-Service | Where-Object -Property Name -match "{{ item }}" | Where-Object -Property Status -match "Running")){
                $services.Add(@{"Name"= $service.Name; "DisplayName" = $service.DisplayName; "Status" = $service.Status.ToString()}) | Out-Null
            }

            $payload = @{
                metrics = @($services)
            } | ConvertTo-Json
            
            echo $payload >> D:\ServiciosRunning_{{ ansible_date_time.date }}.json
      loop: "{{ serivces }}"
