# Windows Disks States
---
- name: Get Current Windows Disks State
  hosts: all
  gather_facts: yes
  tasks:

    - name: Check Disks Health and Sizes 
      ansible.windows.win_powershell:
        script: |
          Get-Volume | select DriveLetter,HealthStatus,Size,SizeRemaining
      register: output_var

    - name: Generate file report
      ansible.windows.win_powershell:
        script: |
          gwmi win32_logicaldisk | Format-Table DeviceId, MediaType, @{n="Size";e={[math]::Round($_.Size/1GB,2)}},@{n="FreeSpace";e={[math]::Round($_.FreeSpace/1GB,2)}} >> C:\Users\Administrator\Documents\reporteEspacioDisco_{{ ansible_date_time.date }}.txt

    - debug:
        msg:
          - "Disco: {{ output_var.output[ansible_loop.index0 - 1].DriveLetter }}"
          - "Estado: {{ output_var.output[ansible_loop.index0 - 1].HealthStatus }}"
          - "Size MB: {{ output_var.output[ansible_loop.index0 - 1].Size }}"
          - "SizeRemaining MB: {{ output_var.output[ansible_loop.index0 - 1].SizeRemaining }}"
      loop: "{{ output_var.output }}"
      loop_control:
        extended: true
        label: "{{ ansible_loop.index0 }}"

    - fetch:
        src: C:\Users\Administrator\Documents\reporteEspacioDisco_{{ ansible_date_time.date }}.txt
        dest: /var/reporteEspacioDisco_{{ ansible_date_time.date }}.txt
        
