# Windows Disks States
---
- name: Get Current Windows Disks State
  hosts: all
  gather_facts: yes
  tasks:

    - name: Check Disks Health and Sizes 
      ansible.windows.win_powershell:
        script: |
          Get-Volume | select DriveLetter,HealthStatus,Size,SizeRemaining
      register: output_var

    - name: Generate file report
      ansible.windows.win_powershell:
        script: |
          gwmi win32_logicaldisk | Format-Table DeviceId, MediaType, @{n="Size";e={[math]::Round($_.Size/1GB,2)}},@{n="FreeSpace";e={[math]::Round($_.FreeSpace/1GB,2)}} >> C:\Users\Administrator\Documents\reporteEspacioDisco_{{ ansible_date_time.date }}.txt

    - debug:
        msg:
          - "Disco: {{ output_var.output[ansible_loop.index0 - 1].DriveLetter }}"
          - "Estado: {{ output_var.output[ansible_loop.index0 - 1].HealthStatus }}"
          - "Size MB: {{ output_var.output[ansible_loop.index0 - 1].Size }}"
          - "SizeRemaining MB: {{ output_var.output[ansible_loop.index0 - 1].SizeRemaining }}"
      loop: "{{ output_var.output }}"
      loop_control:
        extended: true
        label: "{{ ansible_loop.index0 }}"

    - name: Send email report
      mail:
        host: smtp.freesmtpservers.com
        port: 25
        Subject: "Ejecución del estado de los discos ejecutada [Ansible]"
        body: |
          Hola,
          La ejecución de la playbook ha finalizado. Aquí están los resultados de las tareas:

          - "Disco: {{ output_var.output[ansible_loop.index0 - 1].DriveLetter }}"
          - "Estado: {{ output_var.output[ansible_loop.index0 - 1].HealthStatus }}"
          - "Size MB: {{ output_var.output[ansible_loop.index0 - 1].Size }}"
          - "SizeRemaining MB: {{ output_var.output[ansible_loop.index0 - 1].SizeRemaining }}"
          
          Saludos,
          Ansible Automation Platform
        from: testing@ansiblemt.com
        to: yjt10@hotmail.com
        attach:
        - C:\Users\Administrator\Documents\reporteEspacioDisco_{{ ansible_date_time.date }}.txt
        charset: utf8
      loop: "{{ output_var.output }}"
      loop_control:
        extended: true
        label: "{{ ansible_loop.index0 }}"
      delegate_to: localhost
      run_once: true 
